# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: clio - Hydropower module
site_url: https://module_hydropower.readthedocs.io/
repo_name: module_hydropower
repo_url: https://github.com/calliope-project/module_hydropower/
edit_uri: edit/main/docs/
theme:
  name: material
  features:
  - navigation.footer
  - navigation.instant
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.indexes
  - search.suggest
  - search.highlight
  - toc.follow
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      primary: red
      accent: pink
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: red
      accent: pink
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to system preference
      primary: red
      accent: pink
markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.snippets:
      check_paths: true
      restrict_base_path: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - toc:
      anchorlink: true
plugins:
  - search
copyright: Copyright &copy; since 2025 <a href="https://github.com/calliope-project/module_hydropower/blob/main/AUTHORS">module_hydropower contributors</a> (Apache-2.0 licensed)
