[project]
name = "module_hydropower"
version = "0.1.0"
authors = ["See AUTHORS file"]
description = "A module to calculate hydropower generation timeseries for facilities around the globe."
license = "Apache-2.0"
readme = "README.md"
channels = ["conda-forge", "bioconda"]
platforms = ["win-64", "linux-64", "osx-arm64"]
homepage = "https://clio.readthedocs.io/"

[dependencies]
python = ">=3.12"
mkdocs-material = ">=9.6.7"
mypy = ">=1.15.0"
pytest = ">=8.3.5"
ruff = ">=0.9.9"
snakefmt = ">=0.10.2"
conda = ">=25.0.0"
snakemake-minimal = ">=8.29.0"
cffconvert = ">=2.0.0"
clio-tools = ">=2025.03.03"

[pypi-dependencies]
mkdocs-mermaid2-plugin = ">=1.2.1"

[tasks]
test = {cmd = "pytest tests/"}
serve-docs = {cmd = "mkdocs serve"}
build-docs = {cmd = "mkdocs build"}
