# Module settings that users cannot modify.
resources:
  automatic:
    # Links for automatically downloaded files
    dummy_readme: "https://raw.githubusercontent.com/calliope-project/clio/refs/heads/main/README.md"
