# Module settings that users cannot modify.
resources:
  automatic:
    # Links for automatically downloaded files
    HydroBASINS: https://data.hydrosheds.org/file/hydrobasins/standard/hybas_{continent}_lev01-12_v1c.zip
continent_codes: ["af", "ar", "as", "au", "eu", "gr", "na", "sa", "si"]
era5_crs: "epsg:4326"
