# A minimal example of how to configure this module
pfafstetter_level: "06"
years:
  start: 2000
  end: 2000
powerplants:
  basin_adjustment:
    buffer_radius: 1000  # epsg:3857 is in meters
    max_outside: 50
    max_dropped: 30
crs:
  projected: "epsg:3857"
  geographic: "epsg:4326"
smoothing_hours: "168h"
