# A minimal example of how to configure this module
pfafstetter_level: "06"
dates:
  start: "2015-01-01"
  end: "2015-01-15"
powerplants:
  basin_adjustment:
    buffer_radius: 500
    max_dropped: 5
crs:
  projected: "epsg:3857"
  geographic: "epsg:4326"
