name: shell
channels:
  - conda-forge
  - nodefaults
dependencies:
  - atlite = 0.4.0
  - geopandas = 1.0.1
  - ipdb = 0.13.13
  - pandera-geopandas = 0.23.1
  - pyarrow = 19.0.1
  - xarray = 2025.1.2
