name: default
channels:
  - conda-forge
  - nodefaults
dependencies:
  - atlite = 0.4.0
  - geopandas = 1.0.1
  - ipdb = 0.13.13
  - numpy = 2.2.4
  - pandas = 2.2.3
  - pandera-geopandas = 0.24
  - pandera-io = 0.24
  - pyarrow = 19.0.1
  - scipy = 1.15.2
