# Check for changes in the upstream template. If changes are found, a PR is opened.

on:
  pull_request:
    branches:
      - "main"

jobs:
  copier-update:
    permissions:
      contents: write
      pull-requests: write
    uses: calliope-project/clio/.github/workflows/update-copier-template.yml@v2025.03.03
