# Check for changes in the upstream template. If changes are found, an issue is created
name: Template check.
on:
  schedule:
    - cron: '0 0 1 * *' # Runs at 00:00 UTC on the 1st day of every month

jobs:
  copier-update:
    uses: calliope-project/data-module-template/.github/workflows/template-check-version.yml@latest
